# Generated by Django 3.2.7 on 2022-04-28 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dosage', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Counsellingapp.client')),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Counsellingapp.counselor')),
            ],
        ),
        migrations.CreateModel(
            name='update_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Counsellingapp.counselor')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Counsellingapp.session')),
            ],
        ),
        migrations.CreateModel(
            name='SupportGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Counsellingapp.client')),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Counsellingapp.counselor')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='support_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Counsellingapp.supportgroup'),
        ),
        migrations.CreateModel(
            name='MedicationDosage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.PositiveIntegerField()),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Counsellingapp.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Counsellingapp.client')),
            ],
        ),
    ]
